version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: my-node-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root_password
      DATABASE_NAME: my_database

volumes:
  mysql_data:

